CREATE DATABASE IF NOT EXISTS Tasks_Exact;

USE Tasks_Exact;

CREATE TABLE task (
    id INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(30) NOT NULL,
    completed BOOLEAN NOT NULL DEFAULT FALSE
);